version: "3.8"

services:
  ministatus:
    image: rilmay/ministatus:1.0.0  # Stable version
    container_name: ministatus
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    env_file:
      - .env
    restart: unless-stopped 