- name: Grafana
  category: Monitoring
  url: http://localhost:3000
  icon: grafana
- name: Prometheus
  category: Monitoring
  url: http://localhost:9090
  icon: prometheus
- name: Home Assistant
  category: Home Automation
  url: http://localhost:8123
  icon: homeassistant
- name: Pi-hole
  category: Network
  url: http://localhost:8080
  icon: pihole
- name: Proxmox
  category: Servers
  url: https://proxmox.local
  icon: proxmox
- name: Portainer
  category: Containers
  url: http://localhost:9443
  icon: portainer
- name: GitLab
  category: Development
  url: http://gitlab.local
  icon: gitlab
- name: Jenkins
  category: Development
  url: http://localhost:8081
  icon: jenkins
- name: Nextcloud
  category: Storage
  url: http://localhost:8082
  icon: nextcloud
- name: Plex
  category: Media
  url: http://localhost:32400/web
  icon: plex
- name: Syncthing
  category: Storage
  url: http://localhost:8384
  icon: syncthing
- name: Gitea
  category: Development
  url: http://localhost:3001
  icon: gitea
- name: Transmission
  category: Downloads
  url: http://localhost:9091
  icon: transmission
- name: Uptime Kuma
  category: Monitoring
  url: http://localhost:3002
  icon: uptimerobot
- name: Bitwarden
  category: Security
  url: http://localhost:8083
  icon: bitwarden
- name: Vaultwarden
  category: Security
  url: http://localhost:8084
  icon: vaultwarden
- name: Glances
  category: Monitoring
  url: http://localhost:61208
  icon: glances 