#!/usr/bin/env python3
"""
Regenerate requirements-ci-minimal.txt from requirements.txt.

Drops packages not needed for pytest / app imports in CI: gunicorn, anthropic.
Run from repo root: python scripts/sync_requirements_ci_minimal.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "requirements.txt"
OUT = ROOT / "requirements-ci-minimal.txt"

# Strip comments / empties; exclude these PyPI package names (first token before == or >=).
EXCLUDE_NAMES = frozenset({"gunicorn", "anthropic"})


def _package_name(line: str) -> str:
    line = line.strip()
    if not line or line.startswith("#"):
        return ""
    name = line.split("==")[0].split(">=")[0].split("[")[0].strip().lower()
    return name


def main() -> int:
    if not SRC.is_file():
        print(f"Missing {SRC}", flush=True)
        return 1
    kept: list[str] = []
    for line in SRC.read_text(encoding="utf-8").splitlines():
        pkg = _package_name(line)
        if not pkg:
            continue
        if pkg in EXCLUDE_NAMES:
            continue
        kept.append(line.rstrip())

    header = (
        "# Generated by scripts/sync_requirements_ci_minimal.py — do not edit by hand.\n"
        "# Regenerate after changing requirements.txt:\n"
        "#   python scripts/sync_requirements_ci_minimal.py\n"
        "#\n"
    )
    OUT.write_text(header + "\n".join(kept) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(kept)} requirement lines)", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
